/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.util.ArrayList;
import javafx.application.Application;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Anik
 */
public class Frame extends javax.swing.JFrame {

    ArrayList<Person> list=new ArrayList<Person>();
    public Frame() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.ButtonGroup();
        bgSearch = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        imageLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        WelcomePanel = new javax.swing.JPanel();
        WelcomesuccessLabel = new javax.swing.JLabel();
        AdminstratorButton = new javax.swing.JButton();
        nsubuildimageLabel = new javax.swing.JLabel();
        WelcomeLabel = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        AdminstratorPanel = new javax.swing.JPanel();
        LoginLabel = new javax.swing.JLabel();
        AdminloginPanel = new javax.swing.JPanel();
        AdminErrorMassage = new javax.swing.JLabel();
        BackAdButton = new javax.swing.JButton();
        ResetButton = new javax.swing.JButton();
        SubmitButton = new javax.swing.JButton();
        PasswordLabel = new javax.swing.JLabel();
        UserNameTextField = new javax.swing.JTextField();
        UserNameLabel = new javax.swing.JLabel();
        PasswordTextField = new javax.swing.JPasswordField();
        jLabel16 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        AdministratorACPanel = new javax.swing.JPanel();
        SaveAdminstratorrButton = new javax.swing.JButton();
        BackAdminstratorButton = new javax.swing.JButton();
        SearchAdminstratorrButton = new javax.swing.JButton();
        WhatwouldyouLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        SearchPanel = new javax.swing.JPanel();
        SearchPanel1 = new javax.swing.JPanel();
        SearchnotfoundLabel = new javax.swing.JLabel();
        IDRadioButton = new javax.swing.JRadioButton();
        EmailRadioButton = new javax.swing.JRadioButton();
        PhoneRadioButton = new javax.swing.JRadioButton();
        NameRadioButton = new javax.swing.JRadioButton();
        ResetSButton = new javax.swing.JButton();
        BackSButton = new javax.swing.JButton();
        SearchButton = new javax.swing.JButton();
        InputLabel = new javax.swing.JLabel();
        InputTextField = new javax.swing.JTextField();
        SearchMassage = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        SavePanel = new javax.swing.JPanel();
        FirstNameLabel = new javax.swing.JLabel();
        FirstNameTextField = new javax.swing.JTextField();
        LastNameLabel = new javax.swing.JLabel();
        LastNameTextField = new javax.swing.JTextField();
        PhoneLabel = new javax.swing.JLabel();
        PhoneTextField = new javax.swing.JTextField();
        MaleRadioButton = new javax.swing.JRadioButton();
        FRadioButton = new javax.swing.JRadioButton();
        EmailLabel = new javax.swing.JLabel();
        EmailTextField = new javax.swing.JTextField();
        IDLabel = new javax.swing.JLabel();
        IDTextField = new javax.swing.JTextField();
        EmailLabel1 = new javax.swing.JLabel();
        SubmitDataButton = new javax.swing.JButton();
        ResetDataButton = new javax.swing.JButton();
        AddressLabel = new javax.swing.JLabel();
        MonthComboBox = new javax.swing.JComboBox<>();
        DateTextField = new javax.swing.JTextField();
        YearTextField = new javax.swing.JTextField();
        BackAdminButton = new javax.swing.JButton();
        AddressTextArea = new javax.swing.JTextArea();
        jLabel18 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        PersonalInfoPanel = new javax.swing.JPanel();
        Name1Panel = new javax.swing.JPanel();
        NamePersonalLabel = new javax.swing.JLabel();
        IDpersonalLabel = new javax.swing.JLabel();
        PhonepersonallLabel = new javax.swing.JLabel();
        SexpersonalLabel = new javax.swing.JLabel();
        EmailpersonallLabel = new javax.swing.JLabel();
        DateofBirthpersonalLabel = new javax.swing.JLabel();
        AddresspersonallLabel = new javax.swing.JLabel();
        NamePersonal1Label = new javax.swing.JTextField();
        IDpersonal1Label = new javax.swing.JTextField();
        Sexpersonal1Label1 = new javax.swing.JTextField();
        DateofBirthpersonal1Label = new javax.swing.JTextField();
        Phonepersonal1Label = new javax.swing.JTextField();
        Emailpersonal1Label = new javax.swing.JTextField();
        Addresspersonal1Label = new javax.swing.JTextArea();
        PersonalinformationLabel = new javax.swing.JLabel();
        TryAgainpersonalButton = new javax.swing.JButton();
        MainmenupersonalButton = new javax.swing.JButton();
        TextFileButton = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        SuccessPanel = new javax.swing.JPanel();
        submittedsuccessful = new javax.swing.JLabel();
        TryAgainButton = new javax.swing.JButton();
        LogoutSubButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Address Book");
        setBackground(new java.awt.Color(255, 255, 204));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setLayout(null);

        imageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/image/nsu-logo.png"))); // NOI18N
        jPanel1.add(imageLabel);
        imageLabel.setBounds(0, 0, 730, 120);

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.setLayout(new java.awt.CardLayout());

        WelcomePanel.setBackground(new java.awt.Color(255, 255, 204));
        WelcomePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        WelcomesuccessLabel.setFont(new java.awt.Font("Monotype Corsiva", 3, 24)); // NOI18N
        WelcomesuccessLabel.setForeground(new java.awt.Color(0, 51, 0));
        WelcomesuccessLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WelcomePanel.add(WelcomesuccessLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 430, 30));

        AdminstratorButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AdminstratorButton.setText("Continue");
        AdminstratorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminstratorButtonActionPerformed(evt);
            }
        });
        WelcomePanel.add(AdminstratorButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, 90, 30));

        nsubuildimageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nsubuildimageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/image/north-south-university-office.jpg"))); // NOI18N
        WelcomePanel.add(nsubuildimageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, 260));

        WelcomeLabel.setFont(new java.awt.Font("Monotype Corsiva", 3, 36)); // NOI18N
        WelcomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WelcomeLabel.setText("WELCOME");
        WelcomePanel.add(WelcomeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/image/19.jpg"))); // NOI18N
        WelcomePanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 320));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/image/19.jpg"))); // NOI18N
        WelcomePanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, -20, 430, 330));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/image/19.jpg"))); // NOI18N
        WelcomePanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/image/19.jpg"))); // NOI18N
        WelcomePanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, -1, -1));
        WelcomePanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, 0, 780, 470));

        jPanel2.add(WelcomePanel, "card9");

        AdminstratorPanel.setBackground(new java.awt.Color(255, 255, 204));
        AdminstratorPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LoginLabel.setFont(new java.awt.Font("PMingLiU", 1, 36)); // NOI18N
        LoginLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LoginLabel.setText("Log In");
        AdminstratorPanel.add(LoginLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 156, 52));

        AdminloginPanel.setBackground(new java.awt.Color(255, 255, 255));
        AdminloginPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        AdminErrorMassage.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        AdminErrorMassage.setForeground(new java.awt.Color(255, 0, 0));
        AdminErrorMassage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        BackAdButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BackAdButton.setText("Back");
        BackAdButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackAdButtonActionPerformed(evt);
            }
        });

        ResetButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ResetButton.setText("Reset");
        ResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetButtonActionPerformed(evt);
            }
        });

        SubmitButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        SubmitButton.setText("Log In");
        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonActionPerformed(evt);
            }
        });

        PasswordLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PasswordLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PasswordLabel.setText("Password:");

        UserNameTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        UserNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserNameTextFieldActionPerformed(evt);
            }
        });

        UserNameLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        UserNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UserNameLabel.setText("User Name:");

        PasswordTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        PasswordTextField.setToolTipText("");
        PasswordTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AdminloginPanelLayout = new javax.swing.GroupLayout(AdminloginPanel);
        AdminloginPanel.setLayout(AdminloginPanelLayout);
        AdminloginPanelLayout.setHorizontalGroup(
            AdminloginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminloginPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(AdminloginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AdminloginPanelLayout.createSequentialGroup()
                        .addGroup(AdminloginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UserNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(AdminloginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(UserNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                            .addComponent(PasswordTextField))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminloginPanelLayout.createSequentialGroup()
                        .addGroup(AdminloginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(AdminloginPanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(SubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(ResetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                                .addComponent(BackAdButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(AdminErrorMassage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(30, 30, 30))))
        );
        AdminloginPanelLayout.setVerticalGroup(
            AdminloginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminloginPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(AdminloginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UserNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UserNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AdminloginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasswordLabel)
                    .addComponent(PasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AdminErrorMassage, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(AdminloginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SubmitButton)
                    .addComponent(ResetButton)
                    .addComponent(BackAdButton))
                .addGap(41, 41, 41))
        );

        AdminstratorPanel.add(AdminloginPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/image/19.jpg"))); // NOI18N
        AdminstratorPanel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 180, 300, 290));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/image/19.jpg"))); // NOI18N
        AdminstratorPanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/image/19.jpg"))); // NOI18N
        AdminstratorPanel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 0, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/image/19.jpg"))); // NOI18N
        AdminstratorPanel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, -1, 300));
        AdminstratorPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 470));

        jPanel2.add(AdminstratorPanel, "card3");

        AdministratorACPanel.setBackground(new java.awt.Color(255, 255, 204));
        AdministratorACPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SaveAdminstratorrButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SaveAdminstratorrButton.setText("Save ");
        SaveAdminstratorrButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveAdminstratorrButtonActionPerformed(evt);
            }
        });
        AdministratorACPanel.add(SaveAdminstratorrButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 130, 35));

        BackAdminstratorButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BackAdminstratorButton.setText("Log Out");
        BackAdminstratorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackAdminstratorButtonActionPerformed(evt);
            }
        });
        AdministratorACPanel.add(BackAdminstratorButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, 130, 35));

        SearchAdminstratorrButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SearchAdminstratorrButton.setText("Search");
        SearchAdminstratorrButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchAdminstratorrButtonActionPerformed(evt);
            }
        });
        AdministratorACPanel.add(SearchAdminstratorrButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, 130, 35));

        WhatwouldyouLabel.setFont(new java.awt.Font("PMingLiU", 3, 24)); // NOI18N
        WhatwouldyouLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WhatwouldyouLabel.setText("What Would You Like To Do?");
        AdministratorACPanel.add(WhatwouldyouLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 358, 38));

        jLabel1.setFont(new java.awt.Font("PMingLiU", 3, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Greetings...");
        AdministratorACPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 358, 45));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/image/176b94405e74858f95f039b51511369c.jpg"))); // NOI18N
        AdministratorACPanel.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, -1, 470));
        AdministratorACPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 470));

        jPanel2.add(AdministratorACPanel, "card5");

        SearchPanel.setBackground(new java.awt.Color(255, 255, 204));
        SearchPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SearchPanel1.setBackground(new java.awt.Color(255, 255, 255));
        SearchPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        SearchnotfoundLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SearchnotfoundLabel.setForeground(new java.awt.Color(204, 0, 0));
        SearchnotfoundLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        IDRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        IDRadioButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        IDRadioButton.setText("ID");
        IDRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDRadioButtonActionPerformed(evt);
            }
        });

        EmailRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        EmailRadioButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        EmailRadioButton.setText("Email");
        EmailRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailRadioButtonActionPerformed(evt);
            }
        });

        PhoneRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        PhoneRadioButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        PhoneRadioButton.setText("Phone");
        PhoneRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhoneRadioButtonActionPerformed(evt);
            }
        });

        NameRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        NameRadioButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        NameRadioButton.setText("Name");
        NameRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameRadioButtonActionPerformed(evt);
            }
        });

        ResetSButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ResetSButton.setText("Reset");
        ResetSButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetSButtonActionPerformed(evt);
            }
        });

        BackSButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BackSButton.setText("Back");
        BackSButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackSButtonActionPerformed(evt);
            }
        });

        SearchButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        SearchButton.setText("Search");
        SearchButton.setEnabled(false);
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });

        InputLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        InputLabel.setText("Enter Input:");

        javax.swing.GroupLayout SearchPanel1Layout = new javax.swing.GroupLayout(SearchPanel1);
        SearchPanel1.setLayout(SearchPanel1Layout);
        SearchPanel1Layout.setHorizontalGroup(
            SearchPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SearchPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(SearchPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SearchnotfoundLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(SearchPanel1Layout.createSequentialGroup()
                        .addComponent(EmailRadioButton)
                        .addGap(26, 26, 26)
                        .addComponent(IDRadioButton)))
                .addGap(83, 83, 83))
            .addGroup(SearchPanel1Layout.createSequentialGroup()
                .addGroup(SearchPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SearchPanel1Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(SearchButton)
                        .addGap(47, 47, 47)
                        .addComponent(ResetSButton)
                        .addGap(52, 52, 52)
                        .addComponent(BackSButton))
                    .addGroup(SearchPanel1Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(SearchPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NameRadioButton)
                            .addComponent(InputLabel))
                        .addGap(11, 11, 11)
                        .addGroup(SearchPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PhoneRadioButton)
                            .addGroup(SearchPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(InputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        SearchPanel1Layout.setVerticalGroup(
            SearchPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(SearchPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(InputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SearchPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IDRadioButton)
                    .addComponent(EmailRadioButton)
                    .addComponent(PhoneRadioButton)
                    .addComponent(NameRadioButton))
                .addGap(13, 13, 13)
                .addComponent(SearchnotfoundLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(SearchPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ResetSButton)
                    .addComponent(BackSButton)
                    .addComponent(SearchButton))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        SearchPanel.add(SearchPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, -1, -1));

        SearchMassage.setFont(new java.awt.Font("PMingLiU", 3, 36)); // NOI18N
        SearchMassage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SearchMassage.setText("SEARCH");
        SearchPanel.add(SearchMassage, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 264, 42));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/image/176b94405e74858f95f039b51511369c.jpg"))); // NOI18N
        SearchPanel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, -10, -1, 480));
        SearchPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 470));

        jPanel2.add(SearchPanel, "card7");

        SavePanel.setBackground(new java.awt.Color(255, 255, 204));
        SavePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FirstNameLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        FirstNameLabel.setText("First Name:");
        SavePanel.add(FirstNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 36, 94, 29));
        SavePanel.add(FirstNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 40, 130, 24));

        LastNameLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LastNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LastNameLabel.setText("Last Name:");
        SavePanel.add(LastNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 36, 94, 29));
        SavePanel.add(LastNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(521, 40, 130, 24));

        PhoneLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PhoneLabel.setText("Phone:");
        SavePanel.add(PhoneLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 118, 94, 29));
        SavePanel.add(PhoneTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 122, 130, 24));

        MaleRadioButton.setBackground(new java.awt.Color(213, 157, 2));
        MaleRadioButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        MaleRadioButton.setText("M");
        MaleRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaleRadioButtonActionPerformed(evt);
            }
        });
        SavePanel.add(MaleRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(466, 120, -1, -1));

        FRadioButton.setBackground(new java.awt.Color(213, 157, 3));
        FRadioButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        FRadioButton.setText("F");
        FRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FRadioButtonActionPerformed(evt);
            }
        });
        SavePanel.add(FRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 120, -1, -1));

        EmailLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        EmailLabel.setText("Email Address:");
        SavePanel.add(EmailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 165, 112, 29));
        SavePanel.add(EmailTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 169, 166, 24));

        IDLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        IDLabel.setText("ID:");
        SavePanel.add(IDLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 76, 94, 29));
        SavePanel.add(IDTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 80, 130, 24));

        EmailLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        EmailLabel1.setText("Date of Birth:");
        SavePanel.add(EmailLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 337, 104, 29));

        SubmitDataButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        SubmitDataButton.setText("Submit");
        SubmitDataButton.setEnabled(false);
        SubmitDataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitDataButtonActionPerformed(evt);
            }
        });
        SavePanel.add(SubmitDataButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, 100, -1));

        ResetDataButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ResetDataButton.setText("Reset");
        ResetDataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetDataButtonActionPerformed(evt);
            }
        });
        SavePanel.add(ResetDataButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 410, 100, -1));

        AddressLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AddressLabel.setText("Address:");
        SavePanel.add(AddressLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 212, 112, 29));

        MonthComboBox.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        MonthComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May ", "June ", "July", "August", "September", "October", "November", "December" }));
        MonthComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MonthComboBoxActionPerformed(evt);
            }
        });
        SavePanel.add(MonthComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 342, 106, -1));

        DateTextField.setText("Day");
        SavePanel.add(DateTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 343, 70, -1));

        YearTextField.setText("Year");
        SavePanel.add(YearTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 343, 83, -1));

        BackAdminButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BackAdminButton.setText("Back");
        BackAdminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackAdminButtonActionPerformed(evt);
            }
        });
        SavePanel.add(BackAdminButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 410, 100, -1));

        AddressTextArea.setColumns(20);
        AddressTextArea.setLineWrap(true);
        AddressTextArea.setRows(5);
        AddressTextArea.setWrapStyleWord(true);
        SavePanel.add(AddressTextArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 216, -1, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/image/176b94405e74858f95f039b51511369c.jpg"))); // NOI18N
        SavePanel.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, -10, 740, 480));
        SavePanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, 0, 740, 470));

        jPanel2.add(SavePanel, "card6");

        PersonalInfoPanel.setBackground(new java.awt.Color(255, 255, 204));
        PersonalInfoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Name1Panel.setBackground(new java.awt.Color(255, 255, 255));
        Name1Panel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        NamePersonalLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NamePersonalLabel.setText("Name:");

        IDpersonalLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        IDpersonalLabel.setText("ID:");

        PhonepersonallLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PhonepersonallLabel.setText("Phone:");

        SexpersonalLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SexpersonalLabel.setText("Sex:");

        EmailpersonallLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        EmailpersonallLabel.setText("Email:");

        DateofBirthpersonalLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DateofBirthpersonalLabel.setText("Date of Birth:");

        AddresspersonallLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AddresspersonallLabel.setText("Address:");

        NamePersonal1Label.setEditable(false);
        NamePersonal1Label.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        NamePersonal1Label.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamePersonal1LabelActionPerformed(evt);
            }
        });

        IDpersonal1Label.setEditable(false);
        IDpersonal1Label.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        Sexpersonal1Label1.setEditable(false);
        Sexpersonal1Label1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        DateofBirthpersonal1Label.setEditable(false);
        DateofBirthpersonal1Label.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        Phonepersonal1Label.setEditable(false);
        Phonepersonal1Label.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        Emailpersonal1Label.setEditable(false);
        Emailpersonal1Label.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        Addresspersonal1Label.setEditable(false);
        Addresspersonal1Label.setColumns(20);
        Addresspersonal1Label.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Addresspersonal1Label.setLineWrap(true);
        Addresspersonal1Label.setRows(5);
        Addresspersonal1Label.setWrapStyleWord(true);
        Addresspersonal1Label.setBorder(null);

        javax.swing.GroupLayout Name1PanelLayout = new javax.swing.GroupLayout(Name1Panel);
        Name1Panel.setLayout(Name1PanelLayout);
        Name1PanelLayout.setHorizontalGroup(
            Name1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Name1PanelLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(Name1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(Name1PanelLayout.createSequentialGroup()
                        .addComponent(DateofBirthpersonalLabel)
                        .addGap(18, 18, 18)
                        .addComponent(DateofBirthpersonal1Label, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE))
                    .addGroup(Name1PanelLayout.createSequentialGroup()
                        .addComponent(NamePersonalLabel)
                        .addGap(18, 18, 18)
                        .addComponent(NamePersonal1Label))
                    .addGroup(Name1PanelLayout.createSequentialGroup()
                        .addGroup(Name1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SexpersonalLabel)
                            .addComponent(IDpersonalLabel))
                        .addGap(33, 33, 33)
                        .addGroup(Name1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(IDpersonal1Label)
                            .addComponent(Sexpersonal1Label1, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)))
                    .addGroup(Name1PanelLayout.createSequentialGroup()
                        .addGroup(Name1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PhonepersonallLabel)
                            .addComponent(EmailpersonallLabel))
                        .addGap(18, 18, 18)
                        .addGroup(Name1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Emailpersonal1Label, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                            .addComponent(Phonepersonal1Label)))
                    .addGroup(Name1PanelLayout.createSequentialGroup()
                        .addComponent(AddresspersonallLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Addresspersonal1Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(171, Short.MAX_VALUE))
        );
        Name1PanelLayout.setVerticalGroup(
            Name1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Name1PanelLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(Name1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NamePersonalLabel)
                    .addComponent(NamePersonal1Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Name1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IDpersonal1Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IDpersonalLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Name1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SexpersonalLabel)
                    .addComponent(Sexpersonal1Label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Name1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DateofBirthpersonal1Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DateofBirthpersonalLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Name1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Phonepersonal1Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PhonepersonallLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Name1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Emailpersonal1Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmailpersonallLabel))
                .addGap(18, 18, 18)
                .addGroup(Name1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddresspersonallLabel)
                    .addComponent(Addresspersonal1Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        PersonalInfoPanel.add(Name1Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, 350));

        PersonalinformationLabel.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        PersonalinformationLabel.setText("PERSONAL INFORMATION");
        PersonalInfoPanel.add(PersonalinformationLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 338, -1));

        TryAgainpersonalButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TryAgainpersonalButton.setText("Try Again");
        TryAgainpersonalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TryAgainpersonalButtonActionPerformed(evt);
            }
        });
        PersonalInfoPanel.add(TryAgainpersonalButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, 108, -1));

        MainmenupersonalButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        MainmenupersonalButton.setText("Main Menu");
        MainmenupersonalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainmenupersonalButtonActionPerformed(evt);
            }
        });
        PersonalInfoPanel.add(MainmenupersonalButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 410, 110, -1));

        TextFileButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TextFileButton.setText("Text File");
        TextFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFileButtonActionPerformed(evt);
            }
        });
        PersonalInfoPanel.add(TextFileButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 410, 110, -1));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/image/176b94405e74858f95f039b51511369c.jpg"))); // NOI18N
        PersonalInfoPanel.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 470));
        PersonalInfoPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 0, 720, 470));

        jPanel2.add(PersonalInfoPanel, "card8");

        SuccessPanel.setBackground(new java.awt.Color(255, 255, 204));
        SuccessPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        submittedsuccessful.setFont(new java.awt.Font("Script MT Bold", 3, 36)); // NOI18N
        submittedsuccessful.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        submittedsuccessful.setText("Submitted Successful...");
        SuccessPanel.add(submittedsuccessful, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 456, 70));

        TryAgainButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TryAgainButton.setText("Try Again");
        TryAgainButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TryAgainButtonActionPerformed(evt);
            }
        });
        SuccessPanel.add(TryAgainButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 100, -1));

        LogoutSubButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LogoutSubButton.setText("Log Out");
        LogoutSubButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutSubButtonActionPerformed(evt);
            }
        });
        SuccessPanel.add(LogoutSubButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 110, -1));

        BackButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BackButton.setText("Main Menu");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        SuccessPanel.add(BackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, 100, -1));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/image/176b94405e74858f95f039b51511369c.jpg"))); // NOI18N
        SuccessPanel.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 730, 480));
        SuccessPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 470));

        jPanel2.add(SuccessPanel, "card9");

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");

        jMenuItem2.setText("About");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 726, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 726, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 468, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 124, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButtonActionPerformed
        if(UserNameTextField.getText().equals("Anik")&&PasswordTextField.getText().equals("12345")){
            jPanel2.removeAll();
            jPanel2.add(AdministratorACPanel);
            jPanel2.repaint();
            jPanel2.revalidate();
        }else{
            AdminErrorMassage.setText("Username or Password is Incorrect!!!");
        }
    }//GEN-LAST:event_SubmitButtonActionPerformed

    private void ResetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetButtonActionPerformed
        UserNameTextField.setText("");
        PasswordTextField.setText("");
        AdminErrorMassage.setText("");
    }//GEN-LAST:event_ResetButtonActionPerformed

    private void BackAdButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackAdButtonActionPerformed
        WelcomesuccessLabel.setText("");
        jPanel2.removeAll();
            jPanel2.add(WelcomePanel);
            jPanel2.repaint();
            jPanel2.revalidate();
    }//GEN-LAST:event_BackAdButtonActionPerformed

    private void BackAdminstratorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackAdminstratorButtonActionPerformed
        WelcomesuccessLabel.setText("Logged Out Successfully...");
        jPanel2.removeAll();
            jPanel2.add(WelcomePanel);
            jPanel2.repaint();
            jPanel2.revalidate();
    }//GEN-LAST:event_BackAdminstratorButtonActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        bg.add(MaleRadioButton);
        bg.add(FRadioButton);
        bgSearch.add(NameRadioButton);
        bgSearch.add(PhoneRadioButton);
        bgSearch.add(EmailRadioButton);
        bgSearch.add(IDRadioButton);
    }//GEN-LAST:event_formWindowOpened

    private void SubmitDataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitDataButtonActionPerformed
        String str=FirstNameTextField.getText()+" "+LastNameTextField.getText();
        String str2=(String)MonthComboBox.getSelectedItem();
        str2=str2+"/"+DateTextField.getText()+"/"+YearTextField.getText();
        String gender="";
        if(MaleRadioButton.isSelected()){
            gender="Male";
        }
        if(FRadioButton.isSelected()){
            gender="Female";
        }
        Person obj=new Person(str,AddressTextArea.getText(),PhoneTextField.getText(),EmailTextField.getText(),str2,gender,IDTextField.getText());
        list.add(obj);
        jPanel2.removeAll();
            jPanel2.add(SuccessPanel);
            jPanel2.repaint();
            jPanel2.revalidate();
    }//GEN-LAST:event_SubmitDataButtonActionPerformed

    private void MaleRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaleRadioButtonActionPerformed
        SubmitDataButton.setEnabled(true);
    }//GEN-LAST:event_MaleRadioButtonActionPerformed

    private void FRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FRadioButtonActionPerformed
        SubmitDataButton.setEnabled(true);
    }//GEN-LAST:event_FRadioButtonActionPerformed

    private void MonthComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MonthComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MonthComboBoxActionPerformed

    private void ResetDataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetDataButtonActionPerformed
        FirstNameTextField.setText("");
        LastNameTextField.setText("");
        AddressTextArea.setText("");
        EmailTextField.setText("");
        PhoneTextField.setText("");
        IDTextField.setText("");
        DateTextField.setText("");
        YearTextField.setText("");
        MaleRadioButton.setSelected(false);
        FRadioButton.setSelected(false);
        SubmitDataButton.setEnabled(false);
    }//GEN-LAST:event_ResetDataButtonActionPerformed

    private void BackAdminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackAdminButtonActionPerformed
        jPanel2.removeAll();
            jPanel2.add(AdministratorACPanel);
            jPanel2.repaint();
            jPanel2.revalidate();
    }//GEN-LAST:event_BackAdminButtonActionPerformed

    private void SaveAdminstratorrButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveAdminstratorrButtonActionPerformed
        FirstNameTextField.setText("");
        LastNameTextField.setText("");
        AddressTextArea.setText("");
        EmailTextField.setText("");
        PhoneTextField.setText("");
        IDTextField.setText("");
        DateTextField.setText("");
        YearTextField.setText("");
        MaleRadioButton.setSelected(false);
        FRadioButton.setSelected(false);
        SubmitDataButton.setEnabled(false);
        jPanel2.removeAll();
            jPanel2.add(SavePanel);
            jPanel2.repaint();
            jPanel2.revalidate();
    }//GEN-LAST:event_SaveAdminstratorrButtonActionPerformed

    private void TryAgainButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TryAgainButtonActionPerformed
        FirstNameTextField.setText("");
        LastNameTextField.setText("");
        AddressTextArea.setText("");
        EmailTextField.setText("");
        PhoneTextField.setText("");
        IDTextField.setText("");
        DateTextField.setText("");
        YearTextField.setText("");
        MaleRadioButton.setSelected(false);
        FRadioButton.setSelected(false);
        SubmitDataButton.setEnabled(false);
        jPanel2.removeAll();
            jPanel2.add(SavePanel);
            jPanel2.repaint();
            jPanel2.revalidate();
    }//GEN-LAST:event_TryAgainButtonActionPerformed

    private void LogoutSubButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutSubButtonActionPerformed
        WelcomesuccessLabel.setText("Logged Out Successfully...");
        jPanel2.removeAll();
            jPanel2.add(WelcomePanel);
            jPanel2.repaint();
            jPanel2.revalidate();
    }//GEN-LAST:event_LogoutSubButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        jPanel2.removeAll();
            jPanel2.add(AdministratorACPanel);
            jPanel2.repaint();
            jPanel2.revalidate();
    }//GEN-LAST:event_BackButtonActionPerformed

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
        int flag=0;
        if(NameRadioButton.isSelected()){
        for(int i=0;i<list.size();i++){
            if(InputTextField.getText().equalsIgnoreCase(list.get(i).getName())){
                NamePersonal1Label.setText(list.get(i).getName());
                IDpersonal1Label.setText(list.get(i).getID());
                Sexpersonal1Label1.setText(list.get(i).getSex());
                DateofBirthpersonal1Label.setText(list.get(i).getDateofBirth());
                Phonepersonal1Label.setText(list.get(i).getPhone());
                Emailpersonal1Label.setText(list.get(i).getEmail());
                Addresspersonal1Label.setText(list.get(i).getAddress());
                flag=1;
                jPanel2.removeAll();
                jPanel2.add(PersonalInfoPanel);
                jPanel2.repaint();
                jPanel2.revalidate();
                break;
            }
        }
        if(flag==0){
            SearchnotfoundLabel.setText("Match not Found!!!");
        }
    }
        
        if(PhoneRadioButton.isSelected()){
            for(int i=0;i<list.size();i++){
            if(InputTextField.getText().equals(list.get(i).getPhone())){
                NamePersonal1Label.setText(list.get(i).getName());
                IDpersonal1Label.setText(list.get(i).getID());
                Sexpersonal1Label1.setText(list.get(i).getSex());
                DateofBirthpersonal1Label.setText(list.get(i).getDateofBirth());
                Phonepersonal1Label.setText(list.get(i).getPhone());
                Emailpersonal1Label.setText(list.get(i).getEmail());
                Addresspersonal1Label.setText(list.get(i).getAddress());
                flag=1;
                jPanel2.removeAll();
                jPanel2.add(PersonalInfoPanel);
                jPanel2.repaint();
                jPanel2.revalidate();
                break;
            }
        }
        if(flag==0){
            SearchnotfoundLabel.setText("Match not Found!!!");
        }
        }
        
        if(EmailRadioButton.isSelected()){
            for(int i=0;i<list.size();i++){
            if(InputTextField.getText().equalsIgnoreCase(list.get(i).getEmail())){
                NamePersonal1Label.setText(list.get(i).getName());
                IDpersonal1Label.setText(list.get(i).getID());
                Sexpersonal1Label1.setText(list.get(i).getSex());
                DateofBirthpersonal1Label.setText(list.get(i).getDateofBirth());
                Phonepersonal1Label.setText(list.get(i).getPhone());
                Emailpersonal1Label.setText(list.get(i).getEmail());
                Addresspersonal1Label.setText(list.get(i).getAddress());
                flag=1;
                jPanel2.removeAll();
                jPanel2.add(PersonalInfoPanel);
                jPanel2.repaint();
                jPanel2.revalidate();
                break;
            }
        }
        if(flag==0){
            SearchnotfoundLabel.setText("Match not Found!!!");
        }
        }
        
        if(IDRadioButton.isSelected()){
            for(int i=0;i<list.size();i++){
            if(InputTextField.getText().equals(list.get(i).getID())){
                NamePersonal1Label.setText(list.get(i).getName());
                IDpersonal1Label.setText(list.get(i).getID());
                Sexpersonal1Label1.setText(list.get(i).getSex());
                DateofBirthpersonal1Label.setText(list.get(i).getDateofBirth());
                Phonepersonal1Label.setText(list.get(i).getPhone());
                Emailpersonal1Label.setText(list.get(i).getEmail());
                Addresspersonal1Label.setText(list.get(i).getAddress());
                flag=1;
                jPanel2.removeAll();
                jPanel2.add(PersonalInfoPanel);
                jPanel2.repaint();
                jPanel2.revalidate();
                break;
            }
        }
        if(flag==0){
            SearchnotfoundLabel.setText("Match not Found!!!");
        }
        }
        
        
        
    }//GEN-LAST:event_SearchButtonActionPerformed

    private void SearchAdminstratorrButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchAdminstratorrButtonActionPerformed
        InputTextField.setText("");
        SearchnotfoundLabel.setText("");
        NameRadioButton.setSelected(false);
        PhoneRadioButton.setSelected(false);
        EmailRadioButton.setSelected(false);
        IDRadioButton.setSelected(false);
        SearchButton.setEnabled(false);
        jPanel2.removeAll();
            jPanel2.add(SearchPanel);
            jPanel2.repaint();
            jPanel2.revalidate();
    }//GEN-LAST:event_SearchAdminstratorrButtonActionPerformed

    private void NameRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameRadioButtonActionPerformed
        SearchButton.setEnabled(true);
    }//GEN-LAST:event_NameRadioButtonActionPerformed

    private void PhoneRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhoneRadioButtonActionPerformed
        SearchButton.setEnabled(true);
    }//GEN-LAST:event_PhoneRadioButtonActionPerformed

    private void EmailRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailRadioButtonActionPerformed
        SearchButton.setEnabled(true);
    }//GEN-LAST:event_EmailRadioButtonActionPerformed

    private void IDRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDRadioButtonActionPerformed
        SearchButton.setEnabled(true);
    }//GEN-LAST:event_IDRadioButtonActionPerformed

    private void BackSButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackSButtonActionPerformed
        jPanel2.removeAll();
                jPanel2.add(AdministratorACPanel);
                jPanel2.repaint();
                jPanel2.revalidate();
    }//GEN-LAST:event_BackSButtonActionPerformed

    private void ResetSButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetSButtonActionPerformed
        InputTextField.setText("");
        SearchnotfoundLabel.setText("");
        NameRadioButton.setSelected(false);
        PhoneRadioButton.setSelected(false);
        EmailRadioButton.setSelected(false);
        IDRadioButton.setSelected(false);
        SearchButton.setEnabled(false);
    }//GEN-LAST:event_ResetSButtonActionPerformed

    private void TryAgainpersonalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TryAgainpersonalButtonActionPerformed
        InputTextField.setText("");
        SearchnotfoundLabel.setText("");
        NameRadioButton.setSelected(false);
        PhoneRadioButton.setSelected(false);
        EmailRadioButton.setSelected(false);
        IDRadioButton.setSelected(false);
        SearchButton.setEnabled(false);
        jPanel2.removeAll();
                jPanel2.add(SearchPanel);
                jPanel2.repaint();
                jPanel2.revalidate();
    }//GEN-LAST:event_TryAgainpersonalButtonActionPerformed

    private void MainmenupersonalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainmenupersonalButtonActionPerformed
         jPanel2.removeAll();
                jPanel2.add(AdministratorACPanel);
                jPanel2.repaint();
                jPanel2.revalidate();
    }//GEN-LAST:event_MainmenupersonalButtonActionPerformed

    private void AdminstratorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminstratorButtonActionPerformed
        UserNameTextField.setText("");
        PasswordTextField.setText("");
        jPanel2.removeAll();
        jPanel2.add(AdminstratorPanel);
        jPanel2.repaint();
        jPanel2.revalidate();
    }//GEN-LAST:event_AdminstratorButtonActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        new About().setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void TextFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFileButtonActionPerformed
        try{
            FileWriter writer=new FileWriter("C:\\Users\\Anik\\Desktop\\PersonalInfo.txt");
            BufferedWriter bw =new BufferedWriter(writer);
            UserNameTextField.setText("Name: ");
            UserNameTextField.write(bw);
            NamePersonal1Label.write(bw);
            bw.append(System.lineSeparator());
            
            UserNameTextField.setText("ID: ");
            UserNameTextField.write(bw);
            IDpersonal1Label.write(bw);
            bw.append(System.lineSeparator());
            
            UserNameTextField.setText("Sex: ");
            UserNameTextField.write(bw);
            Sexpersonal1Label1.write(bw);
            bw.append(System.lineSeparator());
            
            UserNameTextField.setText("Date of Birth: ");
            UserNameTextField.write(bw);
            DateofBirthpersonal1Label.write(bw);
            bw.append(System.lineSeparator());
            
            UserNameTextField.setText("Phone no: ");
            UserNameTextField.write(bw);
            Phonepersonal1Label.write(bw);
            bw.append(System.lineSeparator());
            
            UserNameTextField.setText("Email no: ");
            UserNameTextField.write(bw);
            Emailpersonal1Label.write(bw);
            bw.append(System.lineSeparator());
            
            UserNameTextField.setText("Address: ");
            UserNameTextField.write(bw);
            Addresspersonal1Label.write(bw);
            bw.append(System.lineSeparator());
            UserNameTextField.setText("");
            
            bw.close();
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_TextFileButtonActionPerformed

    private void NamePersonal1LabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamePersonal1LabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamePersonal1LabelActionPerformed

    private void UserNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserNameTextFieldActionPerformed
        UserNameTextField.setText("");
    }//GEN-LAST:event_UserNameTextFieldActionPerformed

    private void PasswordTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordTextFieldActionPerformed
        PasswordTextField.setText("");
    }//GEN-LAST:event_PasswordTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddressLabel;
    private javax.swing.JTextArea AddressTextArea;
    private javax.swing.JTextArea Addresspersonal1Label;
    private javax.swing.JLabel AddresspersonallLabel;
    private javax.swing.JLabel AdminErrorMassage;
    private javax.swing.JPanel AdministratorACPanel;
    private javax.swing.JPanel AdminloginPanel;
    private javax.swing.JButton AdminstratorButton;
    private javax.swing.JPanel AdminstratorPanel;
    private javax.swing.JButton BackAdButton;
    private javax.swing.JButton BackAdminButton;
    private javax.swing.JButton BackAdminstratorButton;
    private javax.swing.JButton BackButton;
    private javax.swing.JButton BackSButton;
    private javax.swing.JTextField DateTextField;
    private javax.swing.JTextField DateofBirthpersonal1Label;
    private javax.swing.JLabel DateofBirthpersonalLabel;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JLabel EmailLabel1;
    private javax.swing.JRadioButton EmailRadioButton;
    private javax.swing.JTextField EmailTextField;
    private javax.swing.JTextField Emailpersonal1Label;
    private javax.swing.JLabel EmailpersonallLabel;
    private javax.swing.JRadioButton FRadioButton;
    private javax.swing.JLabel FirstNameLabel;
    private javax.swing.JTextField FirstNameTextField;
    private javax.swing.JLabel IDLabel;
    private javax.swing.JRadioButton IDRadioButton;
    private javax.swing.JTextField IDTextField;
    private javax.swing.JTextField IDpersonal1Label;
    private javax.swing.JLabel IDpersonalLabel;
    private javax.swing.JLabel InputLabel;
    private javax.swing.JTextField InputTextField;
    private javax.swing.JLabel LastNameLabel;
    private javax.swing.JTextField LastNameTextField;
    private javax.swing.JLabel LoginLabel;
    private javax.swing.JButton LogoutSubButton;
    private javax.swing.JButton MainmenupersonalButton;
    private javax.swing.JRadioButton MaleRadioButton;
    private javax.swing.JComboBox<String> MonthComboBox;
    private javax.swing.JPanel Name1Panel;
    private javax.swing.JTextField NamePersonal1Label;
    private javax.swing.JLabel NamePersonalLabel;
    private javax.swing.JRadioButton NameRadioButton;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JPasswordField PasswordTextField;
    private javax.swing.JPanel PersonalInfoPanel;
    private javax.swing.JLabel PersonalinformationLabel;
    private javax.swing.JLabel PhoneLabel;
    private javax.swing.JRadioButton PhoneRadioButton;
    private javax.swing.JTextField PhoneTextField;
    private javax.swing.JTextField Phonepersonal1Label;
    private javax.swing.JLabel PhonepersonallLabel;
    private javax.swing.JButton ResetButton;
    private javax.swing.JButton ResetDataButton;
    private javax.swing.JButton ResetSButton;
    private javax.swing.JButton SaveAdminstratorrButton;
    private javax.swing.JPanel SavePanel;
    private javax.swing.JButton SearchAdminstratorrButton;
    private javax.swing.JButton SearchButton;
    private javax.swing.JLabel SearchMassage;
    private javax.swing.JPanel SearchPanel;
    private javax.swing.JPanel SearchPanel1;
    private javax.swing.JLabel SearchnotfoundLabel;
    private javax.swing.JTextField Sexpersonal1Label1;
    private javax.swing.JLabel SexpersonalLabel;
    private javax.swing.JButton SubmitButton;
    private javax.swing.JButton SubmitDataButton;
    private javax.swing.JPanel SuccessPanel;
    private javax.swing.JButton TextFileButton;
    private javax.swing.JButton TryAgainButton;
    private javax.swing.JButton TryAgainpersonalButton;
    private javax.swing.JLabel UserNameLabel;
    private javax.swing.JTextField UserNameTextField;
    private javax.swing.JLabel WelcomeLabel;
    private javax.swing.JPanel WelcomePanel;
    private javax.swing.JLabel WelcomesuccessLabel;
    private javax.swing.JLabel WhatwouldyouLabel;
    private javax.swing.JTextField YearTextField;
    private javax.swing.ButtonGroup bg;
    private javax.swing.ButtonGroup bgSearch;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel nsubuildimageLabel;
    private javax.swing.JLabel submittedsuccessful;
    // End of variables declaration//GEN-END:variables
}
